import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Providers from "@/provider/Providers";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Gym management",
  description: "Generated by create next app",
};

interface Children {
  children: React.ReactNode
}

export default function RootLayout({ children }: Readonly<Children>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}

      >
        <div>
          <Providers>

          {children}
          </Providers>
        </div>
      </body>
    </html>
  );
}
